// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVgUZCbgKpB-iHAJ57ib037AfwqJTVeu4',
    appId: '1:120144568449:web:40c8ff68196d1ce0686d80',
    messagingSenderId: '120144568449',
    projectId: 'auth-c79da',
    authDomain: 'auth-c79da.firebaseapp.com',
    storageBucket: 'auth-c79da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBxYlGoCTpb1d7ZqsaaX3E0Z8n2WYXads',
    appId: '1:120144568449:android:5d3a356668d40e43686d80',
    messagingSenderId: '120144568449',
    projectId: 'auth-c79da',
    storageBucket: 'auth-c79da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoi8qT1TMXqTQdB6t5KH0q7IdJDeK1njY',
    appId: '1:120144568449:ios:49e4c6a8aafeb596686d80',
    messagingSenderId: '120144568449',
    projectId: 'auth-c79da',
    storageBucket: 'auth-c79da.firebasestorage.app',
    iosBundleId: 'com.example.tasteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoi8qT1TMXqTQdB6t5KH0q7IdJDeK1njY',
    appId: '1:120144568449:ios:49e4c6a8aafeb596686d80',
    messagingSenderId: '120144568449',
    projectId: 'auth-c79da',
    storageBucket: 'auth-c79da.firebasestorage.app',
    iosBundleId: 'com.example.tasteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVgUZCbgKpB-iHAJ57ib037AfwqJTVeu4',
    appId: '1:120144568449:web:e1ef78bf28772840686d80',
    messagingSenderId: '120144568449',
    projectId: 'auth-c79da',
    authDomain: 'auth-c79da.firebaseapp.com',
    storageBucket: 'auth-c79da.firebasestorage.app',
  );
}
